# Linear algebra

A linear equation is an algebraic equation in which each term is either a constant or the product of a constant and a single variable. Linear equations can have one, two, or more variables. The term "linear" comes from the fact that the graph of the equation forms a straight line.

## Constants vs variables

### Constant
A constant is a value that does not change. It remains the same regardless of the situation or context. In equations, constants might be numbers like 
5, π, or any fixed value. For example, in the equation y = 3x + 7 the number 7 is a constant because its value is fixed.

### Variable
A variable, on the other hand, represents an unknown value or a value that can change. Variables are often denoted by letters such as x, y, or z. In the context of different mathematical problems, variables can take on different values. For example, in the equation y = 3x + 7 both y and x are variables because their values are not specified and can vary.

#### Difference in Usage
Constants are useful for representing fixed values in mathematical expressions and equations, such as the speed of light or the value of pi, which don’t change.

Variables are used to represent unknowns or quantities that can change. They are particularly useful in equations, functions, and mathematical models where different input values (variables) can generate different outputs.

## Basic Form
Linear equations can be written in various forms depending on the context, but one of the most common ways to express them is the slope-intercept form:

y=mx+b

where y and x are variables,m is the slope of the line (how much 
y increases/decreases as x
x increases by 1), b is the y-intercept (the value of y when x is 0).

### In More Variables

Linear equations can involve more than two variables. For example, in three variables, a linear equation might look like this:

ax+by+cz=d

where a, b, c, and d are constants, and x, y, and z are variables.

### Key Characteristics

The variables are always to the first power and are never multiplied together. The graph of the equation will always be a straight line (in two dimensions) or a plane (in three dimensions).

An example of a linear equation in two dimensions might be:

y=2x+3

In this equation, the slope m is 2, and the y-intercept b is 3. This tells us that for every unit increase in x, y increases by 2, and when x is 0, y is 3.

### Why Important?
Linear equations are foundational in algebra and are used to describe many real-world phenomena. They are also the basis for more advanced mathematical concepts and techniques used in various scientific and engineering disciplines.

## Key Concepts of Linear Algebra
Scalars: A scalar is just a single number, like 3 or -5. Used to scale (multiply) a vector or a matrix. Unlike vectors and matrices, a scalar has no direction or dimensionality. Scalars are typically used to alter the magnitude and/or direction of vectors without altering their spatial orientation.

Vectors: A vector is an ordered array of numbers, which can represent things like coordinates in space. For example, \[2,3,4] is a 3-dimensional vector.

Matrices: A matrix is a 2-dimensional array of numbers, arranged in rows and columns, and can represent a set of linear equations or transformations of vectors. For instance,

\[\[1,2,3], 
\[4,5,6],
\[7,8,9]

is a 3x3 matrix.

Linear Equations: These are equations that represent straight lines when graphed, and have the form ax+by+cz=d in 3 dimensions.

Systems of Linear Equations: A set of linear equations that share variables. For example:

3x+4y=5
2x−y=1
 
## Operations in Linear Algebra
* Addition and Subtraction: Vectors and matrices can be added or subtracted element-wise.
* Scalar Multiplication: Multiplying a vector or a matrix by a scalar involves multiplying each element by the scalar.
* Dot Product: The dot product of two vectors is the sum of the products of their corresponding components.
* Matrix Multiplication: Involves multiplying the rows of the first matrix by the columns of the second matrix.
* Transposition: Swapping the rows and columns of a matrix.
* Determinant and Inverse: The determinant is a special number derived from a square matrix, and the inverse of a matrix, if it exists, is a matrix that, when multiplied with the original matrix, gives the identity matrix.

## Vectors

Vectors are defined as quantities having both direction and magnitude, compared to scalar quantities that only have magnitude. In order to have direction and magnitude, vector quantities consist of two or more elements of data. The dimensionality of a vector is determined by the number of numerical elements in that vector. For example, a vector with four elements would have a dimensionality of four.

Let’s take a look at examples of a scalar versus a vector. A car driving at a speed of 40mph is a scalar quantity. Describing the car driving 40mph to the east would represent a two-dimensional vector quantity since it has a magnitude in both the x and y directions.

Vectors can be represented as a series of numbers enclosed in parentheses, angle brackets, or square brackets. In this lesson, we will use square brackets for consistency. For example, a three-dimensional vector is written as:

v = \[xyz]

​The magnitude (or length) of a vector, ||v||, can be calculated with the sum of each vector component squared.

<img src="Assets/vector-magnitude.png">

Let’s look at an example. We are told that a ball is traveling through the air and given the velocities of that ball in its x, y, and z directions in a standard Cartesian coordinate system. The velocity component values are:

In [21]:
import math

x = (-12) ** 2
y = 8 ** 2
z = (-2) ** 2

v = math.sqrt(x + y + z)
print(v)

14.560219778561036


### Scalar multiplication

Any vector can be multiplied by a scalar, which results in every element of that vector being multiplied by that scalar individually.

k\[xyz] = \[kx ky kz]

Multiplying vectors by scalars is an associative operation, meaning that rearranging the parentheses in the expression does not change the result. For example, we can say 2(a3) = (2a)3.

### Vector Addition and Subtraction

Vectors can be added and subtracted from each other when they are of the same dimension (same number of components). Doing so adds or subtracts corresponding elements, resulting in a new vector of the same dimension as the two being summed or subtracted. Below is an example of three-dimensional vectors being added and subtracted together.

<img src="Assets/vector-add.png">

Vector addition is commutative, meaning the order of the terms does not matter. For example, we can say (a+b = b+a). Vector addition is also associative, meaning that (a + (b+c) = (a+b) + c).

## Dot products

A dot product takes two equal dimension vectors and returns a single scalar value by summing the products of the vectors’ corresponding components.

To find the dot product of the two vectors:

a = \[3 2 -3]
b = \[0 -3 -6]

a • b = 3 * 0 + 2 * -3 + -3 * 6 = 12
a • b = 12

The dot product operation is both commutative (a · b = b · a) and distributive (a · (b+c) = a · b + a · c).

The resulting scalar value represents how much one vector “goes into” the other vector. If two vectors are perpendicular (or orthogonal), their dot product is equal to 0, as neither vector “goes into the other.”

The dot product can also be used to find the magnitude of a vector and the angle between two vectors. To find the magnitude, we can see that the magnitude of a vector is simply the square root of a vector’s dot product with itself.

||a|| = √ A • A

To find the angle between two vectors, we rely on the dot product between the two vectors and use the following equation.

θ = arccos a•b / ||a|| ||b||

9+4+9

In [22]:
print(math.sqrt(22))

4.69041575982343


## Matrices

A matrix is a quantity with m rows and n columns of data. For example, we can combine multiple vectors into a matrix where each column of that matrix is one of the vectors.

scalar = 1

vector = \[1 2]

matrix = 

\[\[1 2], 

\[3, 4]]

The shape of a matrix is said to be mxn, where there are m rows and n columns. When representing matrices as a variable, we denote the matrix with a capital letter and a particular matrix element as the matrix variable with an “m,n” determined by the element’s location. Let’s look at an example of this. Consider the matrix below.

<img src="Assets/matrix.png">

The value corresponding to the first row and second column is b.

A₁,₂ = b

A₂,₃ = f

## Matrix operations

We can both multiply entire matrices by a scalar value, as well as add or subtract matrices with equal shapes.

Matrix multiplication works by computing the dot product between each row of the first matrix and each column of the second matrix. For example, in computing AB = C, element (1,2) of the matrix product C will be the dot product of row 1 of matrix A and column 2 of matrix B.

An important rule about matrix multiplication is that the shapes of the two matrices AB must be such that the number of columns in A is equal to the number of rows in B. With this condition satisfied, the resulting matrix product will be the shape of rowsA x columnsB. For example, in the animation to the right, the product of a 2x3 matrix and a 3x2 matrix ends up being a 2x2 matrix.

Based on how we compute the product matrix with dot products and the importance of having correctly shaped matrices, we can see that matrix multiplication is not commutative, AB ≠ BA. However, we can also see that matrix multiplication is associative, A(BC) = (AB)C.

In [3]:
import numpy as np

# NumPy vector array
v = np.array([1, 2, 3, 4, 5, 6])

# Two-dimensional matrix (nested lists)
A = np.array([[1,2],[3,4]])

# Matrices can be made by combining vectors
v = np.array([-2,-2,-2,-2])
u = np.array([0,0,0,0])
w = np.array([3,3,3,3])

A = np.column_stack((v, u, w))
print(A)

[[-2  0  3]
 [-2  0  3]
 [-2  0  3]
 [-2  0  3]]


In [4]:
# Find the shape of a matrix
print(A.shape) # 4 rows and 3 columns

(4, 3)


In [5]:
# Access values

print(A[0,2]) # Row then column, zero-indexed

3


In [6]:
print(A[:,1]) # Get all of col 2

[0 0 0 0]


In [7]:
print(A[3,:]) # Get all of row 4

[-2  0  3]


### Algebra


In [22]:
# Multiplies every value in matrix by 4
A = np.array([[1,2],[3,4]])
print(4 * A) 

[[1 2]
 [3 4]]


In [10]:
# Adds values in two matrices together
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])
print(A + B)

[[-3 -1]
 [ 1  3]]


In [13]:
# Dot function
v = np.array([-1,-2,-3])
u = np.array([2,2,2])
print(np.dot(v,u))

-12


In [14]:
# Matrix multiplication 
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])

# one way to matrix multiply
# np.matmul(A,B)
# another way to matrix multiply
print(A@B)

[[ -8  -5]
 [-20 -13]]


In [15]:
# Identity matrix
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# Zeroes matrix
zero_matrix = np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Transpose matrix
A = np.array([[1,2],[3,4]])
A_transpose = A.T
print(A_transpose)

[[1 3]
 [2 4]]


In [19]:
# Norm (length/magitude of vector)
v = np.array([2,-4,1])
v_norm = np.linalg.norm(v)
print(v_norm)

4.58257569495584


In [23]:
#Inverse of a square matrix
A = np.array([[2,4,-2],[-2,0,1],[3,-3,0]])
print(np.linalg.inv(A))

[[0.5        1.         0.66666667]
 [0.5        1.         0.33333333]
 [1.         3.         1.33333333]]


#### Solve for unknown variables
Given:
4x + z = 2
-y + 2z - 3x = 0
.5y - x - 1.5z = -4

In [26]:
A = np.array([[1, -3, 1],[2, -8, 8],[-6, 3, -15]])
b = np.array([4, -2, 9])
x,y,z = np.linalg.solve(A,b)
print((x,y,z))

(3.0000000000000013, -1.0000000000000002, -2.0000000000000004)
